#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# npx husky add .husky/commit-msg "npx --no-install commitlint -e $HUSKY_GIT_PARAMS"
npx --no-install commitlint -e
# npx --no-install commitlint --edit $1
